/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_protocol_JProtocol */

#ifndef _Included_org_jnetpcap_protocol_JProtocol
#define _Included_org_jnetpcap_protocol_JProtocol
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: PAYLOAD */
/* Inaccessible static: ETHERNET */
/* Inaccessible static: IP4 */
/* Inaccessible static: IP6 */
/* Inaccessible static: TCP */
/* Inaccessible static: UDP */
/* Inaccessible static: IEEE_802DOT3 */
/* Inaccessible static: IEEE_802DOT2 */
/* Inaccessible static: IEEE_SNAP */
/* Inaccessible static: IEEE_802DOT1Q */
/* Inaccessible static: L2TP */
/* Inaccessible static: PPP */
/* Inaccessible static: ICMP */
/* Inaccessible static: HTTP */
/* Inaccessible static: HTML */
/* Inaccessible static: WEB_IMAGE */
/* Inaccessible static: ARP */
/* Inaccessible static: SIP */
/* Inaccessible static: SDP */
/* Inaccessible static: RTP */
/* Inaccessible static: SLL */
#undef org_jnetpcap_protocol_JProtocol_PAYLOAD_ID
#define org_jnetpcap_protocol_JProtocol_PAYLOAD_ID 0L
#undef org_jnetpcap_protocol_JProtocol_ETHERNET_ID
#define org_jnetpcap_protocol_JProtocol_ETHERNET_ID 1L
#undef org_jnetpcap_protocol_JProtocol_IP4_ID
#define org_jnetpcap_protocol_JProtocol_IP4_ID 2L
#undef org_jnetpcap_protocol_JProtocol_IP6_ID
#define org_jnetpcap_protocol_JProtocol_IP6_ID 3L
#undef org_jnetpcap_protocol_JProtocol_TCP_ID
#define org_jnetpcap_protocol_JProtocol_TCP_ID 4L
#undef org_jnetpcap_protocol_JProtocol_UDP_ID
#define org_jnetpcap_protocol_JProtocol_UDP_ID 5L
#undef org_jnetpcap_protocol_JProtocol_IEEE_802DOT3_ID
#define org_jnetpcap_protocol_JProtocol_IEEE_802DOT3_ID 6L
#undef org_jnetpcap_protocol_JProtocol_IEEE_802DOT2_ID
#define org_jnetpcap_protocol_JProtocol_IEEE_802DOT2_ID 7L
#undef org_jnetpcap_protocol_JProtocol_IEEE_SNAP_ID
#define org_jnetpcap_protocol_JProtocol_IEEE_SNAP_ID 8L
#undef org_jnetpcap_protocol_JProtocol_IEEE_802DOT1Q_ID
#define org_jnetpcap_protocol_JProtocol_IEEE_802DOT1Q_ID 9L
#undef org_jnetpcap_protocol_JProtocol_L2TP_ID
#define org_jnetpcap_protocol_JProtocol_L2TP_ID 10L
#undef org_jnetpcap_protocol_JProtocol_PPP_ID
#define org_jnetpcap_protocol_JProtocol_PPP_ID 11L
#undef org_jnetpcap_protocol_JProtocol_ICMP_ID
#define org_jnetpcap_protocol_JProtocol_ICMP_ID 12L
#undef org_jnetpcap_protocol_JProtocol_HTTP_ID
#define org_jnetpcap_protocol_JProtocol_HTTP_ID 13L
#undef org_jnetpcap_protocol_JProtocol_HTML_ID
#define org_jnetpcap_protocol_JProtocol_HTML_ID 14L
#undef org_jnetpcap_protocol_JProtocol_WEB_IMAGE_ID
#define org_jnetpcap_protocol_JProtocol_WEB_IMAGE_ID 15L
#undef org_jnetpcap_protocol_JProtocol_ARP_ID
#define org_jnetpcap_protocol_JProtocol_ARP_ID 16L
#undef org_jnetpcap_protocol_JProtocol_SIP_ID
#define org_jnetpcap_protocol_JProtocol_SIP_ID 17L
#undef org_jnetpcap_protocol_JProtocol_SDP_ID
#define org_jnetpcap_protocol_JProtocol_SDP_ID 18L
#undef org_jnetpcap_protocol_JProtocol_RTP_ID
#define org_jnetpcap_protocol_JProtocol_RTP_ID 19L
#undef org_jnetpcap_protocol_JProtocol_SLL_ID
#define org_jnetpcap_protocol_JProtocol_SLL_ID 20L
/* Inaccessible static: LAST_ID */
/* Inaccessible static: _00024VALUES */
#ifdef __cplusplus
}
#endif
#endif
