/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_PcapPacket */

#ifndef _Included_org_jnetpcap_packet_PcapPacket
#define _Included_org_jnetpcap_packet_PcapPacket
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: directMemory */
/* Inaccessible static: directMemorySoft */
#undef org_jnetpcap_packet_PcapPacket_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_PcapPacket_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
/* Inaccessible static: POINTER */
#undef org_jnetpcap_packet_PcapPacket_DEFAULT_STATE_HEADER_COUNT
#define org_jnetpcap_packet_PcapPacket_DEFAULT_STATE_HEADER_COUNT 20L
/* Inaccessible static: defaultScanner */
/* Inaccessible static: out */
/* Inaccessible static: pool */
/* Inaccessible static: STATE_SIZE */
/*
 * Class:     org_jnetpcap_packet_PcapPacket
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_PcapPacket_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
